source "https://rubygems.org"

gem "bootsnap", require: false
gem "dotenv-rails", "~> 2.1", ">= 2.1.1"
gem "kamal", require: false
gem "pg", "~> 1.5", ">= 1.5.9"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "rails", "~> 8.0.2"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "thruster", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "brakeman", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
end
